language: python

python:
    - 2.7

install:
    - pip install -r requirements.py
    - nvm install 0.10
    - npm install

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - nosetests --with-coverage --coverage-module=gluuwebui
    - npm test
